# Generated by Django 4.2.5 on 2023-09-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LocationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('details', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('banner_image', models.ImageField(upload_to='media')),
                ('normal_image', models.ImageField(upload_to='media')),
                ('is_banner', models.BooleanField(default=False)),
                ('is_best_deals', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LocationApp.location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PackageApp.packagetype')),
            ],
        ),
    ]
