# Generated by Django 4.2.5 on 2023-09-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
        ('PackageApp', '0002_alter_package_name_alter_packagetype_name'),
        ('BookingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HotelApp.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PackageApp.packagetype'),
        ),
    ]
