# Generated by Django 4.2.5 on 2023-12-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0003_hotel_banner_image_hotel_normal_image'),
        ('PackageApp', '0002_alter_package_name_alter_packagetype_name'),
        ('BookingApp', '0004_alter_booking_hotel_name_alter_booking_packagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApp.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PackageApp.package'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PackageApp.packagetype'),
        ),
    ]
