# Generated by Django 4.2.5 on 2023-12-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0006_alter_booking_booking_status_alter_booking_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='packageName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='typeName',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
